site_name: Dokumentation Projektarbeit

repo_name: /projektarbeit
repo_url: https://github.com/gz-bad-erzland-p3/projektarbeit/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Überblick:
    - index.md
  - Anleitungen & Informationen:
    - anleitungen/index.md
  - Projektphasen:
    - Projektdefinition:
      - Protokoll: projektdefinition/protokoll.md
      - Lastenheft: projektdefinition/lastenheft.md
      - Pflichtenheft: projektdefinition/pflichtenheft.md
    - Projektentwurf: projektentwurf.md
    - Projektdurchführung:
      - Anwendungsentwicklung:
        - Frontend: projektdurchführung/anwendungsentwicklung/frontend.md
        - Backend: projektdurchführung/anwendungsentwicklung/backend.md
        - Probleme: projektdurchführung/anwendungsentwicklung/probleme.md
      - Systemintegration:
        - Netzwerk: projektdurchführung/systemintegration/netzwerk.md
        - Webserver: projektdurchführung/systemintegration/webserver.md
        - Monitoring: projektdurchführung/systemintegration/monitoring.md
        - Automatisierung Website: projektdurchführung/systemintegration/automatisierung.md
        - Firewall: projektdurchführung/systemintegration/firewall.md
        - DNS: projektdurchführung/systemintegration/dns.md

plugins:
  - search

extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

theme:
  name: material
  language: de
  logo: assets/logo.png
  favicon: assets/logo.png

  custom_dir: docs/overrides

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - toc.follow
    - navigation.indexes
    - content.code.annotate
  
  font:
    text: Roboto
    code: Roboto Mono
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css