site_name: Dokumentation Projektarbeit

repo_name: /projektarbeit
repo_url: https://github.com/gz-bad-erzland-p3/projektarbeit/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Startseite:
    - index.md
  - Projektdefinition:
    - projektdefinition.md
  - Projektdurchführung:
    - projektdurchfuehrung.md
  - Projektentwurf:
    - projektentwurf.md

plugins:
  - search

theme:
  name: material
  language: de
  logo: assets/logo.svg
  favicon: assets/logo.svg

  custom_dir: docs/overrides

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.follow
    - navigation.indexes
    - content.code.annotate
  font:
    text: Roboto
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css